apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charongroups.ipman.dialo.ai
spec:
  group: ipman.dialo.ai
  names:
    kind: CharonGroup
    listKind: CharonGroupList
    plural: charongroups
    singular: charongroup
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - hostNetwork
                - nodeName
              properties:
                hostNetwork:
                  type: boolean
                nodeName:
                  type: string
                interfaceName:
                  type: string
                charonExtraAnnotations:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties: {}
      subresources:
        status: {}
