apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRoleName }}
# TODO: limit this as much as possible
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "update", "create", "watch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "create", "list", "watch"]
- apiGroups: ["ipman.dialo.ai"]
  resources: ["ipsecconnections"]
  verbs: ["get", "list", "update", "create", "watch"]
- apiGroups: ["ipman.dialo.ai"]
  resources: ["ipsecconnections/status"]
  verbs: ["get", "update", "create", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "list", "get", "watch", "update"]
