apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ipman.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipman.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "ipman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ipman.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ipman.serviceAccountName" . }}
      {{- with .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          env:
            - name: NAMESPACE_NAME
              value: {{ .Values.global.namespace }}
            - name: XFRMINION_IMAGE
              value: {{ .Values.xfrminion.image }}
            - name: VXLANDLORD_IMAGE
              value: {{ .Values.vxlandlord.image }}
            - name: RESTCTL_IMAGE
              value: {{ .Values.restctl.image }}
            - name: XFRMINJECTOR_IMAGE
              value: {{ .Values.xfrminjector.image }}
            - name: CHARONDAEMON_IMAGE
              value: {{ .Values.charon.image }}
            - name: CADDY_IMAGE
              value: {{ .Values.caddy.image }}
            - name: PROXY_SOCKET_PATH
              value: {{ .Values.global.socketPath }}
            - name: HOST_SOCKETS_PATH
              value: {{ .Values.global.socketPath }}
            - name: XFRMINION_PULL_POLICY
              value: {{ .Values.xfrminion.pullPolicy }}
            - name: XFRMINJECTOR_PULL_POLICY
              value: {{ .Values.xfrminjector.pullPolicy }}
            - name: XFRMINJECTOR_TTL_SECONDS
              value: "{{ .Values.xfrminjector.ttlSeconds }}"
            - name: CHARON_PULL_POLICY
              value: {{ .Values.charon.pullPolicy }}
            - name: RESTCTL_PULL_POLICY
              value: {{ .Values.restctl.pullPolicy }}
            - name: PROXY_PULL_POLICY
              value: {{ .Values.caddy.pullPolicy }}
            - name: POD_WAIT_TIMEOUT
              value: "{{ .Values.controller.podTimeoutSeconds }}"
            - name: MONITORING_ENABLED
              value: "{{ .Values.global.monitoring.enabled }}"
            - name: MONITORING_SCRAPE_INTERVAL
              value: "{{ .Values.global.monitoring.interval }}"
            - name: MONITORING_RELEASE_NAME
              value: "{{ .Values.global.monitoring.release}}"

          volumeMounts:
          - name: {{ .Values.webhook.volumes.name }}
            mountPath: {{ .Values.webhook.volumes.mountPath }}
            readOnly: {{ .Values.webhook.volumes.readOnly }}
      volumes:
      - name: {{ .Values.webhook.volumes.name }}
        secret:
          secretName: {{ .Values.webhook.certificate.secretName }}
