apiVersion: v1
kind: Service
metadata:
  name: ipman-restctl-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector: 
    ipman.dialo.ai/type: "restctl"
  ports:
  - protocol: TCP
    port: 61410
    targetPort: 61410
