apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.systemNamespace}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . }}
  {{- end}}
