# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
# Controller (operator) configuration
controller:
  replicaCount: 1
  image: "plan9better/operator:0.0.7"
  pullPolicy: Always
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
# Restctl service configuration
restctl:
  image: "plan9better/restctl:0.0.7"
# VxlanLord configuration
vxlandlord:
  image: "plan9better/vxlandlord:0.0.7"
# XfrmMinion configuration
xfrminion:
  image: "plan9better/xfrminion:0.0.7"
# Charon daemon configuration
charon:
  image: "plan9better/strongswan-charon:0.0.7"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}
