apiVersion: ipman.dialo.ai/v1
kind: Ipman
metadata:
  name: sodies-nix
  namespace: default
spec:
  name: "connection-name"
  remoteAddr: "xxx.xxx.xxx.xxx/xx"
  localAddr: "xxx.xxx.xxx.xxx/xx"
  localId: "xxx.xxx.xxx.xxx/xx"
  remoteId: "xxx.xxx.xxx.xxx/xx"
  secretRef:
    name: "ipsec-secret"
    namespace: "default"
    key: "psk"
  children:
    - name: "child-name"
      localTs: "10.0.2.0/24"
      remoteTs: "10.0.1.0/24"
  nodeName: "node-01"
