apiVersion: ipman.dialo.ai/v1
kind: Ipman
metadata:
  name: sodies-nix
  namespace: ims
spec:
  name: "3s"
  remoteAddr: "xxx.xxx.xxx.xxx"
  localAddr: "xxx.xxx.xxx.xxx"
  localId: "xxx.xxx.xxx.xxx"
  remoteId: "xxx.xxx.xxx.xxx"
  secretRef:
    name: "ipsec-secret"
    namespace: "default"
    key: "psk"
  children:
    - name: "3s"
      local_ips:
        - "10.0.2.0/24"
      remote_ips:
        - "10.0.1.0/24"
      xfrm_ip: "10.0.2.1/24"
      vxlan_ip: "10.0.2.2/24"
      if_id: 102
      ip_pools:
        primary:
          - "10.0.2.3/24"
          - "10.0.2.4/24"
          - "10.0.2.5/24"
          - "10.0.2.6/24"
        secondary:
          - "10.0.2.7/24"
          - "10.0.2.8/24"
          - "10.0.2.9/24"
          - "10.0.2.10/24"
    - name: "4s"
      local_ips: 
        - "10.0.4.4/32"
        - "10.0.9.8/32"
        - "10.0.2.9/32"
        - "10.0.4.3/32"
        - "10.0.3.11/32"
        - "10.0.23.20/32"
      remote_ips: 
        - "10.0.3.1/32"
        - "10.0.3.3/32"
        - "10.0.3.7/32"
      xfrm_ip: "10.0.9.1/32"
      vxlan_ip: "10.0.8.2/32"
      if_id: 202
      ip_pools:
        worker:
          - "10.0.9.8/32"
          - "10.0.2.9/32"
        manager:
          - "10.0.4.3/32"
          - "10.0.3.11/32"
          - "10.0.23.20/32"
          - "10.0.4.4/32"
  nodeName: "nixos"
