apiVersion: v1
kind: Pod
metadata:
  name: xfrmpod
  annotations:
    Ipmanaged: "true"
  labels:
    name: xfrmpod
spec:
  containers:
  - name: xfrm
    image: ubuntu:latest
    command: ["sh", "-c", "apt update && apt install iproute2 -y && while true; do sleep 10000; done"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]

