
apiVersion: v1
kind: Service
metadata:
  name: ipman-webhook-service
  namespace: ims
spec:
  ports:
  - port: 443
    name: "webhook"
    protocol: TCP
    targetPort: 8443

  - port: 61410
    name: "state"
    protocol: TCP
    targetPort: 61410

  selector:
    app.kubernetes.io/name: ipman
    control-plane: controller-manager
