apiVersion: v2
appVersion: "0.1.17"
description: IPSec connection manager
name: ipman
type: application
version: 0.1.17
annotations:
  artifacthub.io/category: "networking"
  artifacthub.io/crds: |
    - kind: IPSecConnection
      version: v1
      name: ipsecconnection
      description: Defines the connection to a remote site
  artifacthub.io/license: MIT
  artifacthub.io/recommendations: |
    - https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
