apiVersion: v2
appVersion: 1.16.0
description: IPSec connection manager
name: ipman
type: application
annotations:
  artifacthub.io/category: "networking"
  artifacthub.io/images: |
    - name: xfrminion
      image: plan9better/xfrminion:0.1.10
      platforms:
        - linux/amd64
    - name: vxlandlord
      image: plan9better/vxlandlord:0.1.10
      platforms:
        - linux/amd64
    - name: operator
      image: plan9better/operator:0.1.10
      platforms:
        - linux/amd64
    - name: restctl
      image: plan9better/restctl:0.1.10
      platforms:
        - linux/amd64
    - name: charon
      image: plan9better/charon:0.1.10
      platforms:
        - linux/amd64
  artifacthub.io/crds: |
    - kind: IPSecConnection
      version: v1
      name: ipsecconnection
      description: Defines the connection to a remote site
  artifacthub.io/license: MIT
  artifacthub.io/recommendations: |
    - https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
version: 0.1.10
