# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
  monitoring:
    enabled: false
    interval: 10s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "192.168.10.201:5000/operator:latest-dev"
  pullPolicy: Always
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
  pullPolicy: "Always"
# Restctl service configuration
restctl:
  image: "192.168.10.201:5000/restctl:latest-dev"
  pullPolicy: "Always"
# Xfrminjector configuration
xfrminjector:
  image: "192.168.10.201:5000/xfrminjector:latest-dev"
  pullPolicy: "Always"
  ttlSeconds: 120
# VxlanLord configuration
vxlandlord:
  image: "192.168.10.201:5000/vxlandlord:latest-dev"
  pullPolicy: "Always"
# XfrmMinion configuration
xfrminion:
  image: "192.168.10.201:5000/xfrminion:latest-dev"
  pullPolicy: "Always"
# Charon daemon configuration
charon:
  image: "192.168.10.201:5000/charon:latest-dev"
  pullPolicy: "Always"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}
