# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
  monitoring:
    enabled: false
    interval: 10s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "ghcr.io/dialohq/ipman/operator@sha256:914ec5150773024b8c31dec2954305087ae65b0dcc5f7bca3b0dca051e4baac2"
  pullPolicy: Always
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
  pullPolicy: "Always"
# Restctl service configuration
restctl:
  image: "ghcr.io/dialohq/ipman/restctl@sha256:527ebc1f8ad2227b35461fffb81947f43d2dd2e3b7aee34b6d3da3efad761b75"
  pullPolicy: "Always"
# Xfrminjector configuration
xfrminjector:
  image: "ghcr.io/dialohq/ipman/xfrminjector@sha256:45406f54e0f79cb8bdbe99562bf179e4fc7e0323a0acc4a6cf812fb382d55b68"
  pullPolicy: "Always"
  ttlSeconds: 120
# VxlanLord configuration
vxlandlord:
  image: "ghcr.io/dialohq/ipman/vxlandlord@sha256:a2b81eb0e36a689e7e29f964dc82d74edcf99e93ccaff1bd6cb870f74b9c25ea"
  pullPolicy: "Always"
# XfrmMinion configuration
xfrminion:
  image: "ghcr.io/dialohq/ipman/xfrminion@sha256:ffc52db20dbeaa57d3a1b53b4cd2db70e2770b78e4a5e76f7eff9aaff3280e28"
  pullPolicy: "Always"
# Charon daemon configuration
charon:
  image: "plan9better/charon:latest-dev"
  pullPolicy: "Always"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}

---
